from bdsh.service.rpc import RPCSocketClient


class BadLogonClient(RPCSocketClient):
    def __init__(self): ...

    def save(self) -> None: ...

    def load(self): ...

    def add(self, username, password): ...

    def get_user_by_credentials(self, username, password): ...

    def validate_username(self, username): ...
