[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bdsh"
authors = [
    { name = "Logan Dhillon", email = "dev@logandhillon.com" }
]
dynamic = ["version"]
description = "BadOS Dynamic Shell"
requires-python = ">=3.10"
readme = "README.md"
keywords = ["shell", "terminal", "cli", "command-line", "BadOS", "operating-system"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: System :: Shells",
    "Topic :: Terminals"
]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://badtechnologies.github.io/bdsh"
Documentation = "https://badtechnologies.github.io/bdsh"
Repository = "https://github.com/badtechnologies/bdsh"
Issues = "https://github.com/badtechnologies/bdsh/issues"

[project.scripts]
bdsh = "bdsh.__main__:main"
bdsh-daemon = "bdsh.daemon.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = { attr = "bdsh.__version__.__version__" }