from bdsh.service.rpc import RPCSocketClient


class NetworkClient(RPCSocketClient):
    def __init__(self): ...

    def hostname(self) -> str: ...

    def interfaces(self) -> dict: ...

    def interface_addresses(self) -> dict: ...

    def resolve(self, hostname: str) -> str: ...
